In [10]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
import joblib

X = df[['HourOfCall', 'distance', 'distance_stat', 'pop_per_stat', 'bor_sqkm']]
y = df['AttendanceTimeClasses3']
y = y - 1 

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xclf = xgb.XGBClassifier(learning_rate=0.1, max_depth=8, n_estimators=400)
xclf.fit(X_train, y_train)
joblib.dump(xclf, 'XGBoost3kurz.pkl')

y_pred = xclf.predict(X_test)
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)
print('ClassificationReport:')
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[  8389  13939    634     74     13      7]
 [  4134 125400  10093    211     36      8]
 [   289  26698  22344    710     48     15]
 [    65   2853   4314   1147    111     29]
 [    30    758    841    336    102     20]
 [    25    432    337    123     54     25]]
ClassificationReport:
              precision    recall  f1-score   support

           0       0.65      0.36      0.47     23056
           1       0.74      0.90      0.81    139882
           2       0.58      0.45      0.50     50104
           3       0.44      0.13      0.21      8519
           4       0.28      0.05      0.08      2087
           5       0.24      0.03      0.05       996

    accuracy                           0.70    224644
   macro avg       0.49      0.32      0.35    224644
weighted avg       0.68      0.70      0.67    224644



In [7]:
df = pd.read_csv('/Users/Kivik11_1/Downloads/df_mi5.csv', index_col=0)